# =============================================================================
# api/services/citation_verifier.py
# Milestone 4 — Citation Verification Engine (CRITIC 1)
# Ensures arguments generated by the LLM are strictly grounded in the
# provided retrieved authorities.
# =============================================================================

import logging
from typing import List, Dict, Any, Tuple
from api.models.retrieval import RetrievedAuthorityV2

logger = logging.getLogger("opposing_simulator.verifier")

def verify_citations(
    generated_arguments: List[Dict[str, Any]],
    retrieved_authorities: List[RetrievedAuthorityV2]
) -> Tuple[List[Dict[str, Any]], float]:
    """
    Checks each generated argument's supporting authorities against the exact set 
    of retrieved authorities passed into the generation request.
    
    Returns:
        - The modified list of arguments (with 'unverified' flags added).
        - The Grounding Verification score (G_v) between 0.0 and 1.0.
    """
    valid_citations = {auth.citation.lower() for auth in retrieved_authorities}
    valid_case_names = {auth.case_name.lower() for auth in retrieved_authorities}
    
    total_citations = 0
    verified_citations = 0
    
    for arg in generated_arguments:
        authorities = arg.get("supporting_authority", [])
        
        # If the LLM didn't provide an authority but claimed it's a legal argument,
        # we might penalize it, but for now we just verify what is provided.
        for auth in authorities:
            total_citations += 1
            citation = auth.get("citation", "").lower()
            
            # Allow matching on exact citation string OR case name as a fallback.
            # Real LLMs sometimes slightly mangle the format.
            is_verified = False
            if citation in valid_citations:
                is_verified = True
            else:
                # Fuzzy fallback: check if citation string contains a valid case name
                for case_name in valid_case_names:
                    if case_name in citation:
                        is_verified = True
                        break
            
            if is_verified:
                verified_citations += 1
            else:
                auth["unverified"] = True
                
        # If any authority in this argument is unverified, downgrade confidence
        has_unverified = any(a.get("unverified", False) for a in authorities)
        if has_unverified and arg.get("confidence") == "High":
            arg["confidence"] = "Medium" # Downgrade due to grounding risk
            
    # Calculate G_v (Grounding Verification)
    if total_citations == 0:
        # If no citations were made at all, it's 0% verified (since the prompt demands citations).
        g_v = 0.0
    else:
        g_v = verified_citations / total_citations
        
    logger.info(f"Citation Verification Complete. G_v = {g_v:.2f} ({verified_citations}/{total_citations})")
    
    return generated_arguments, g_v
