export const DISCLAIMER_FULL = `
This tool is an educational simulation only. It does not provide legal advice, legal representation, or legal counsel of any kind. 
The opposing arguments generated by this system are simulated and may not reflect actual law in your jurisdiction. They are generated for practice purposes only. 
Use of this application does not create an attorney-client relationship. The creators of this tool are not responsible for any legal decisions you make based on this simulation.
`;

export const DISCLAIMER_COMPACT = "EDUCATIONAL SIMULATION ONLY: This is not legal advice. The arguments below are simulated for practice.";
