import Head from 'next/head';
import Link from 'next/link';
import Layout from '@/components/Layout';

const HOW_IT_WORKS = [
  {
    step: '01',
    title: 'Submit Your Case',
    desc: 'Fill in the intake form with your party names, claim type, jurisdiction, key dates, and the facts of your case.',
    icon: '📋',
  },
  {
    step: '02',
    title: 'AI Analyses the Opposition',
    desc: 'Our system retrieves relevant case law and generates the strongest arguments the opposing side is likely to make.',
    icon: '🤖',
  },
  {
    step: '03',
    title: 'Practise Your Rebuttals',
    desc: 'Review each argument, note weaknesses, and write your counter-arguments to walk into court prepared.',
    icon: '⚖️',
  },
];

const FEATURES = [
  { icon: '📚', title: 'Real Case Law',         desc: 'Grounded in Harvard CAP legal database (Milestone 2)' },
  { icon: '🎯', title: 'Jurisdiction-Aware',    desc: 'Filters authorities to your specific state or federal court' },
  { icon: '💬', title: 'Rebuttal Workspace',    desc: 'Write and organise counter-arguments for each point' },
  { icon: '📄', title: 'Export to PDF',         desc: 'Print your preparation notes for court (Milestone 4)' },
  { icon: '🔒', title: 'Privacy-First',         desc: 'No account required; sessions are not stored' },
  { icon: '♿', title: 'Fully Accessible',      desc: 'WCAG 2.1 AA compliant — built for everyone' },
];

const FAQ = [
  {
    q: 'Is this legal advice?',
    a: 'No. This is an educational simulation only. The opposing arguments are generated by AI and may not accurately reflect the law in your jurisdiction. Always consult a qualified attorney.',
  },
  {
    q: 'How accurate are the arguments?',
    a: 'In Milestone 1 all responses are clearly-labelled mock data. From Milestone 2 onwards, arguments are grounded in retrieved case law from the Harvard Caselaw Access Project.',
  },
  {
    q: 'Who is this for?',
    a: 'Self-represented litigants (people without lawyers) who want to understand what the other side might argue so they can prepare better responses.',
  },
  {
    q: 'What legal areas are covered?',
    a: 'Breach of contract, negligence, employment discrimination, landlord-tenant disputes, personal injury, and property disputes across all U.S. jurisdictions.',
  },
];

export default function HomePage() {
  return (
    <Layout>
      <Head>
        <title>Opposing-Argument Simulator — Legal Preparation for Self-Represented Litigants</title>
      </Head>

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section className="text-center py-16 md:py-24 relative">
        {/* Background glow */}
        <div
          aria-hidden="true"
          className="absolute inset-0 -z-10 overflow-hidden"
        >
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-navy-800/40 rounded-full blur-3xl" />
        </div>

        <div className="inline-flex items-center gap-2 bg-gold-500/10 border border-gold-500/30 rounded-full px-4 py-1.5 text-gold-400 text-xs font-semibold mb-6">
          <span className="w-1.5 h-1.5 rounded-full bg-gold-400 animate-pulse-slow" />
          Milestone 1 — Scaffold Live
        </div>

        <h1 className="text-4xl md:text-6xl font-black text-white mb-6 leading-tight">
          Know What the{' '}
          <span className="text-gold-400">Other Side</span>
          <br />
          Will Argue
        </h1>

        <p className="text-navy-300 text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed">
          An educational AI simulation that generates opposing counsel arguments so
          self-represented litigants can walk into court prepared — not surprised.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link href="/intake" id="hero-cta-intake" className="btn-primary text-base px-8 py-3.5">
            Start Case Intake →
          </Link>
          <Link href="/simulation" id="hero-cta-simulation" className="btn-outline text-base px-8 py-3.5">
            View Simulation Demo
          </Link>
        </div>

        <p className="text-navy-500 text-xs mt-6">
          ⚖️ Educational simulation only — not legal advice
        </p>
      </section>

      {/* ── How It Works ─────────────────────────────────────────────────── */}
      <section aria-labelledby="how-it-works-heading" className="py-16">
        <div className="text-center mb-12">
          <h2 id="how-it-works-heading" className="section-heading">How It Works</h2>
          <p className="section-subheading">Three steps to better court preparation</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {HOW_IT_WORKS.map(({ step, title, desc, icon }) => (
            <div key={step} className="card text-center group hover:border-navy-600 transition-colors">
              <div className="text-4xl mb-4" aria-hidden="true">{icon}</div>
              <div className="text-gold-500 text-xs font-black tracking-widest mb-2">
                STEP {step}
              </div>
              <h3 className="text-white font-bold text-lg mb-3">{title}</h3>
              <p className="text-navy-300 text-sm leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="divider" />

      {/* ── Features Grid ─────────────────────────────────────────────────── */}
      <section aria-labelledby="features-heading" className="py-16">
        <div className="text-center mb-12">
          <h2 id="features-heading" className="section-heading">Features</h2>
          <p className="section-subheading">Everything you need to prepare your defence</p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {FEATURES.map(({ icon, title, desc }) => (
            <div
              key={title}
              className="card-glass group hover:border-navy-600 hover:bg-navy-800/60 transition-all duration-200"
            >
              <div className="text-2xl mb-3" aria-hidden="true">{icon}</div>
              <h3 className="text-white font-semibold mb-1.5">{title}</h3>
              <p className="text-navy-400 text-sm">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="divider" />

      {/* ── FAQ ──────────────────────────────────────────────────────────── */}
      <section aria-labelledby="faq-heading" className="py-16">
        <div className="text-center mb-12">
          <h2 id="faq-heading" className="section-heading">Frequently Asked Questions</h2>
        </div>

        <div className="max-w-3xl mx-auto space-y-4">
          {FAQ.map(({ q, a }, i) => (
            <div key={i} className="card">
              <h3 className="text-white font-semibold mb-2">{q}</h3>
              <p className="text-navy-300 text-sm leading-relaxed">{a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA Banner ───────────────────────────────────────────────────── */}
      <section className="py-16">
        <div className="card-glass text-center border-gold-500/20 py-12">
          <h2 className="text-3xl font-black text-white mb-4">
            Ready to Prepare Your Case?
          </h2>
          <p className="text-navy-300 mb-8 max-w-xl mx-auto">
            Submit your case facts and receive a set of opposing arguments to practise against.
          </p>
          <Link href="/intake" id="bottom-cta-intake" className="btn-primary text-base px-10 py-4">
            Start Case Intake →
          </Link>
        </div>
      </section>
    </Layout>
  );
}
