import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { Button } from '@/components/ui/Button';
import { DisclaimerOverlay } from '@/components/ui/DisclaimerOverlay';
import styles from './index.module.css';

export default function LandingPage() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Opposing-Argument Simulator</title>
        <meta name="description" content="Practice Your Case Against an AI Opponent" />
      </Head>

      <DisclaimerOverlay 
        title="MANDATORY LEGAL DISCLAIMER"
        content="This tool provides educational practice only and is not a substitute for qualified attorney representation. Any information generated by this simulator should not be considered legal advice. By continuing, you acknowledge that you are using this tool for educational preparation purposes only."
        acceptText="I Understand & Continue"
        onAccept={() => console.log('Disclaimer accepted')}
      />

      <main className={styles.main}>
        <div className={styles.header}>
          <h1 className={styles.title}>OPPOSING-ARGUMENT SIMULATOR</h1>
          <p className={styles.subtitle}>Practice Your Case Against an AI Opponent</p>
        </div>

        <div className={styles.valueProps}>
          <div className={styles.card}>
            <div className={styles.cardIcon}>👤</div>
            <h3>YOU</h3>
            <p>Prepare Your Case</p>
          </div>
          <div className={styles.card}>
            <div className={styles.cardIcon}>⚖️</div>
            <h3>PRACTICE</h3>
            <p>Against an AI Opponent</p>
          </div>
          <div className={styles.card}>
            <div className={styles.cardIcon}>🎯</div>
            <h3>MASTER</h3>
            <p>Your Case Before Court</p>
          </div>
        </div>

        <div className={styles.heroImage}>
          <div className={styles.heroLeft}>
            <Image src="/user_avatar.png" alt="You - The Litigant" width={150} height={150} className={styles.heroAvatar} />
          </div>
          <div className={styles.heroVersus}>VS</div>
          <div className={styles.heroRight}>
            <Image src="/opponent_avatar.png" alt="Opposing Counsel" width={150} height={150} className={styles.heroAvatar} />
          </div>
        </div>

        <div className={styles.ctaContainer}>
          <Button 
            size="lg" 
            className={styles.ctaButton}
            onClick={() => router.push('/intake?step=1')}
          >
            START YOUR CASE
          </Button>
          <div className={styles.demoLink}>
            Or watch 2-min demo video
          </div>
        </div>
      </main>
    </div>
  );
}
